version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV = development
      - FLASK_APP = app.py
    volumes:
      - ./app:/app
    depends_on:
      - db
    working_dir: /app
    command: python app.py
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: DASAK # grubun adı baş harflerimiz
      MYSQL_ROOT_PASSWORD: dasak
    volumes:
      - ./db/db-data:/var/lib/mysql # db data diye bi şey açıyor bu sayede container kapanınca data gitmiyo
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # cretae command'leri sql çalışınca runlanacak yere mount'luyor
volumes:
  db-data: